logging.level.org.springframework=INFO
logging.level.com.scalable=INFO
logging.level.com.zaxxer=ERROR
logging.level.root=ERROR

spring.datasource.hikari.connectionTimeout=20000
spring.datasource.hikari.maximumPoolSize=5

# logging.pattern.console=%-5level %logger{36} - %msg%n

## MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/inventorydb
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.dialect.storage_engine=innodb
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=none


# hibernate_sequence' doesn't exist
# spring.jpa.hibernate.use-new-id-generator-mappings=false

# drop n create table again, good for testing, comment this in production
#spring.jpa.hibernate.ddl-auto=create-drop